### ISSUE TITLE
Markdown-ify the paper and rename the repo

### ISSUE THREAD

**Issue by mrigankpawagi** [mrigankpawagi/EfficientAttention-TermPaper#1]
Maybe in the README? (Should we do this at all?)

**Comment by sahil-chaudhary** [comment]
Hmm, won't take much time to be honest if we are just going to copy our paper idea. It depends how organize do we want it to be?

You could rename the repo to just **Efficient Attention**.

**Comment by mrigankpawagi** [comment]
I have added some, maybe you can add more. Its mostly copy-paste from LaTeX with slight changes.

**Comment by mrigankpawagi** [comment]
Need to fix some math mode errors though!

**Comment by mrigankpawagi** [comment]
Done. Please check @sahil-chaudhary @Nagasai561 @irenicquasar and fix any errors you see.

**Comment by sahil-chaudhary** [comment]
@mrigankpawagi, I  didn't find any errors in the summary. It is mostly inspired from our original paper summary. 

Also, should we add a collab link to our pynb file(collab one)?

**Comment by mrigankpawagi** [comment]
Yes, it is the exact same but with some changes made to take care of markdown syntax. @sahil-chaudhary 

As for the notebooks -- you can just link the notebooks in the repo itself because GitHub has now added support for viewing notebooks.

**Comment by mrigankpawagi** [comment]
But yeah collab link may be better. You can create it.

**Comment by sahil-chaudhary** [comment]
I have created the colab link and added in the description at the very last. One can also choose to access the experiments using pynb file which I had already added.
