### ISSUE TITLE
Modifications

### ISSUE THREAD

**Issue by mrigankpawagi** [mrigankpawagi/EfficientAttention-TermPaper#2]
I noticed some forking of this repository and figured that the purpose might be to present it on one's profile. However, I noticed that the repository itself was not very presentable. I have done some cleanup and organization, but it would be nice if someone could edit the README to clearly document what each file/directory in the repository does. Please then open a PR with the same.

**Comment by sahil-chaudhary** [comment]
Yeah. I can manage time in the night I suppose (possibly in the night). Nevertheless, I might be withdrawing the document for the same purpose. I have decided something else to do.

Anyway, I might add few other experiments for the same.
